name: CI

on: [push, workflow_dispatch]
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
          ruby-version: '3.0'
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

